---
title: "AY_Tests"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Packages
```{r Load packages, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE, results='hide'}
library(tidyverse)
library(readxl)
library(broom)
library(cowplot)
library(phyloseq)
library(vegan)
set.seed(7)
```

#Phylum Data Frame with Only Desired Columns
```{r}
#Creating Processed Phylum Data Frame:
phylum_processed_df <- phylum_avg_shared %>%
  rename_all(tolower) %>%
  filter(study_week == "week1" | study_week == "week3") %>%
  select("participant_id", "semester", "study_week", "firmicutes", "bacteroidetes <bacteroidetes>") %>%
  rename(., "bacteroidetes" = "bacteroidetes <bacteroidetes>") %>%
  mutate(., f_b_ratio = firmicutes/bacteroidetes)

#Checking Sample Sizes for Consistency by Week:
phylum_processed_df %>%
  filter(study_week == "week1") %>%
  summarise(sample_size = n()) # n = 508

phylum_processed_df %>%
  filter(study_week == "week3") %>%
  summarise(sample_size = n()) # n = 480. 508-480 = 28 inconsistencies. 

#Split by Weeks and Recombine so only samples with both weeks present: 
phylum_week1 <- phylum_processed_df %>%
  filter(study_week == "week1")

phylum_week3 <- phylum_processed_df %>%
  filter(study_week == "week3")
phylum_week3

phylum_processed_df_both_weeks_present <- inner_join(phylum_week1, phylum_week3, by = (c("participant_id")))

#Final Data Frames:
phylum_processed_df
phylum_processed_df_both_weeks_present

phylum_processed_df_both_weeks_present_final <- phylum_processed_df_both_weeks_present %>%
  rename(firmicutes_wk1 = firmicutes.x, bacteroidetes_wk1 = bacteroidetes.x, fb_ratio_wk1 =  
  f_b_ratio.x, firmicutes_wk3 = firmicutes.y, bacteroidetes_wk3 = bacteroidetes.y, fb_ratio_wk3 = 
  f_b_ratio.y, semester = semester.x) %>%
  select(-starts_with("study_week"), -starts_with("semester.y"))
View(phylum_processed_df_both_weeks_present_final)

#Save Plots: 
write_delim(phylum_processed_df, path = "~/Desktop/phylum_processed_df.txt",
            delim = "\t", col_names = TRUE, quote = FALSE)
write_delim(phylum_processed_df_both_weeks_present, path = "~/Desktop/phylum_processed_df_both_weeks_present.txt",
            delim = "\t", col_names = TRUE, quote = FALSE)
write_delim(phylum_processed_df_both_weeks_present_final, path = "~/Desktop/phylum_processed_df_both_weeks_present_final.txt",
            delim = "\t", col_names = TRUE, quote = FALSE)
```

